### ISSUE TITLE
Additional logging data from K8s metadata

### ISSUE THREAD

**Issue by bfowle** [clustergarage/fim-k8s#10]
Configurable and pass into `logFormat`
- name of fimwatcher
- deploy/pod labels
- annotations

**Comment by bfowle** [comment]
Holding until we have an option for JSON-logging instead of the custom log message. This way we can dump any metadata about the deployment along with the rest of the info.

**Comment by akentosh** [comment]
Second that. It doesn't hurt to provide as much information about the vulnerable application as possible. That being said, custom tags provides a lot of flexibility and I'm not sure we need more.
