### ISSUE TITLE
Technical Documentation

### ISSUE THREAD

**Issue by bfowle** [clustergarage/fim-k8s#2]
The documentation and architecture on `fimd` and `fim-controller` repos (just in a README for now?):
- [x] prerequisites
  - [x] permission to watch procfs, docker.sock, docker.pid, cgroups
  - [x] multi-tenancy environment will not work due to permissions needed
- [x] configuration params and how they work
  - [x] `selector`
  - [x] `subjects` array (`events`/`paths` as single/multiple, `recursive`, `ignore`, `onlyDir` flags)
  - [x] `logFormat`
- [x] how the controller interacts with the k8s lifecycle, system
- [x] how the daemon spawns child processes for inotify, mqueue, etc.
- [x] how the daemon finds PID given a containerID
- [x] how the controller<-->daemon interacts with each other
- [x] running, stopping these components
- [x] what permissions (scc in openshift, etc.) they require
- [x] creating a FimWatcher for an app deployment, other kinds; and what syntax it expects; using multiple events/paths different ways
- [x] caveats around symlinks, and other procfs gotchas we haven't quite mastered yet (see details of findings and examples at: https://github.com/clustergarage/fimd/issues/9)
- [x] running controller with an out-of-cluster `-fimd 0.0.0.0:50051` flag locally on minikube or other vm-based solutions, will act differently since it find the pid via cgroups on the host
- [x] `fimcontroller` replicas should be `1` generally; if having >1 it will cause the same event to be fired to the daemon multiple times, which should be idempotent already-- you may just get a `create` followed by an `update`
- [x] `fimd` should schedule out to all nodes that can handle compute -- if it has a `taint` then an explicit `toleration` will need to be added to the `fimd` demonset to schedule them out on these; this will not be an option that we provide, it will be up to the user based on their use-case
- [x] cleaning up CRDs manually since `delete all --all` doesnt delete  custom types in namespace

**Comment by akentosh** [comment]
Let's step through this tomorrow, especially sections around defining a watcher.
